package com.example.newsewingworkshop

object MyIntentConstants {
    const val I_NAME_KEY = "name_key"
    const val I_LASTNAME_KEY = "lastname_key"
    const val I_PHONENUMBER_KEY = "phonenumber_key"
    const val I_DESCRIPTION_KEY = "description_key"
    const val I_ETDIS_KEY = "etDis_key"
    const val I_ETOSH_KEY = "etOsh_key"
    const val I_ETOG1_KEY = "etOg1_key"
    const val I_ETOG2_KEY = "etOg2_key"
    const val I_ETOG3_KEY = "etOg3_key"
    const val I_ETOTA_KEY = "etOta_key"
    const val I_ETOB_KEY = "etOb_key"
    const val I_ETDT_B_KEY = "etDt_b_key"
    const val I_ETSHG_KEY = "etSHg_key"
    const val I_ETSHG2_KEY = "etSHg2_key"
    const val I_ETSHS_KEY = "etSHs_key"
    const val I_ETSHP_KEY = "etSHp_key"
    const val I_ETDTP_KEY = "etDtp_key"
    const val I_ETDTS_KEY = "etDts_key"
    const val I_ETVG_KEY = "etVg_key"
    const val I_ETCG_KEY = "etCg_key"
    const val I_ETVPKP_KEY = "etVpkp_key"
    const val I_ETVPKS_KEY = "etVpks_key"
    const val I_ETVPRZ_KEY = "etVprz_key"
    const val I_ETDR_KEY = "etDr_key"
    const val I_ETOR_KEY = "etOr_key"
    const val I_ETOZAP_KEY = "etOzap_key"
    const val I_ETDUB_KEY = "etDub_key"
    const val I_ETDSP_KEY = "etDsp_key"
    const val I_ETDZB_KEY = "etDzb_key"
    const val I_ETDZZ_KEY = "etDzz_key"
    const val I_ETDB_KEY = "etDb_key"
    const val I_ETVS_KEY = "etVs_key"
    const val I_ETOBED_KEY = "etObed_key"
    const val I_ETDT_K_KEY = "etDt_k_key"
    const val I_ETSHK_KEY = "etSHk_key"
    const val I_ETSHN_KEY = "etSHn_key"
}